"""Best-effort overlay Portfiles from brew source URLs. Does not classify."""

from __future__ import annotations

import re
from dataclasses import dataclass
from pathlib import Path
from typing import Optional

from brew_to_ports.models import Package

SHAPE_GITHUB_NOARCH = "github_noarch"
SHAPE_GOLANG = "golang"
SHAPE_AUTORECONF = "autoreconf"

_SKIP_BUILD = {
    "cmake",
    "meson",
    "ninja",
    "rust",
    "cargo",
    "maturin",
    "go",
    "python",
    "perl",
}
_GITHUB_ARCHIVE = re.compile(
    r"^https://github\.com/([^/]+)/([^/]+)/archive/(?:refs/tags/)?(.+)\.(?:tar\.gz|tgz)$",
    re.I,
)


@dataclass
class TryRecipe:
    shape: str
    port_name: str
    category: str
    portfile: str


def default_overlay_root() -> Path:
    from brew_to_ports.paths import workspace_logs_dir

    return workspace_logs_dir() / "overlay"


def recipe_for(pkg: Package) -> Optional[TryRecipe]:
    """None if we will not invent a Portfile."""
    if "@" in pkg.name or not pkg.source_url or not pkg.sha256:
        return None
    if pkg.kind != "formula":
        return None
    gh = _parse_github(pkg.source_url)
    builds = {_base(b) for b in pkg.build_deps}
    if "cmake" in builds or "meson" in builds or "rust" in builds or "maturin" in builds:
        return None
    if "go" in builds:
        if gh is None:
            return None
        return _golang_recipe(pkg, gh)
    if gh is None:
        return None
    if "autoconf" in builds or "automake" in builds or "libtool" in builds:
        return _autoreconf_recipe(pkg, gh)
    if builds - {"pkgconf", "pkg-config", "pkgconfig"}:
        return None
    return _noarch_recipe(pkg, gh)


def write_overlay(pkg: Package, root: Path) -> Optional[Path]:
    rec = recipe_for(pkg)
    if rec is None:
        return None
    portdir = root / rec.category / rec.port_name
    portdir.mkdir(parents=True, exist_ok=True)
    (portdir / "Portfile").write_text(rec.portfile, encoding="utf-8")
    return portdir


def _base(name: str) -> str:
    return name.split("@", 1)[0].lower()


def _parse_github(url: str):
    m = _GITHUB_ARCHIVE.match(url.strip())
    if not m:
        return None
    owner, repo, tag = m.group(1), m.group(2), m.group(3)
    repo = re.sub(r"\.git$", "", repo)
    if tag.startswith("v") and len(tag) > 1 and tag[1].isdigit():
        version, prefix = tag[1:], "v"
    else:
        version, prefix = tag, ""
    return owner, repo, version, prefix, tag


def _license(raw: str) -> str:
    s = (raw or "unknown").split()[0]
    s = s.split("OR")[0].strip()
    mapping = {
        "MIT": "MIT",
        "Apache-2.0": "Apache-2",
        "BSD-2-Clause": "BSD",
        "BSD-3-Clause": "BSD",
        "GPL-3.0-only": "GPL-3",
        "GPL-3.0-or-later": "GPL-3",
        "GPL-2.0-only": "GPL-2",
        "Artistic-1.0-Perl": "Artistic-1",
    }
    return mapping.get(s, "unknown")


def _tcl_brace(s: str) -> str:
    return "{" + s.replace("\\", "\\\\").replace("{", "\\{").replace("}", "\\}") + "}"


def _noarch_recipe(pkg: Package, gh) -> TryRecipe:
    owner, repo, version, prefix, _tag = gh
    prefix_line = f"github.setup        {owner} {repo} {version} {prefix}".rstrip()
    desc = _tcl_brace(pkg.description or pkg.name)
    portfile = f"""# -*- coding: utf-8; mode: tcl; tab-width: 4; indent-tabs-mode: nil; c-basic-offset: 4 -*- vim:fenc=utf-8:ft=tcl:et:sw=4:ts=4:sts=4
# generated by brew-to-ports --try-source; best-effort overlay, not a formula translator

PortSystem          1.0
PortGroup           github 1.0

{prefix_line}
github.tarball_from archive
revision            0
categories          sysutils
license             {_license(pkg.license)}
maintainers         nomaintainer
description         {desc}
long_description    ${{description}}
checksums           sha256 {pkg.sha256}
supported_archs     noarch
platforms           any
use_configure       no
build               {{}}

destroot {{
    xinstall -d ${{destroot}}${{prefix}}/share/${{name}}
    copy {{*}}[glob ${{worksrcpath}}/*] ${{destroot}}${{prefix}}/share/${{name}}
    if {{[file exists ${{worksrcpath}}/bin/${{name}}]}} {{
        ln -s ${{prefix}}/share/${{name}}/bin/${{name}} ${{destroot}}${{prefix}}/bin/${{name}}
    }}
}}
"""
    return TryRecipe(SHAPE_GITHUB_NOARCH, pkg.name, "sysutils", portfile)


def _golang_recipe(pkg: Package, gh) -> TryRecipe:
    owner, repo, version, prefix, _tag = gh
    tag_arg = f" {prefix}" if prefix else ""
    desc = _tcl_brace(pkg.description or pkg.name)
    portfile = f"""# -*- coding: utf-8; mode: tcl; tab-width: 4; indent-tabs-mode: nil; c-basic-offset: 4 -*- vim:fenc=utf-8:ft=tcl:et:sw=4:ts=4:sts=4
# generated by brew-to-ports --try-source; best-effort overlay, not a formula translator

PortSystem          1.0
PortGroup           golang 1.0

go.setup            github.com/{owner}/{repo} {version}{tag_arg}
go.offline_build    no
revision            0
categories          devel
license             {_license(pkg.license)}
maintainers         nomaintainer
description         {desc}
long_description    ${{description}}
checksums           sha256 {pkg.sha256}
"""
    return TryRecipe(SHAPE_GOLANG, pkg.name, "devel", portfile)


def _autoreconf_recipe(pkg: Package, gh) -> TryRecipe:
    owner, repo, version, prefix, _tag = gh
    prefix_line = f"github.setup        {owner} {repo} {version} {prefix}".rstrip()
    desc = _tcl_brace(pkg.description or pkg.name)
    portfile = f"""# -*- coding: utf-8; mode: tcl; tab-width: 4; indent-tabs-mode: nil; c-basic-offset: 4 -*- vim:fenc=utf-8:ft=tcl:et:sw=4:ts=4:sts=4
# generated by brew-to-ports --try-source; best-effort overlay, not a formula translator

PortSystem          1.0
PortGroup           github 1.0

{prefix_line}
github.tarball_from archive
revision            0
categories          net
license             {_license(pkg.license)}
maintainers         nomaintainer
description         {desc}
long_description    ${{description}}
checksums           sha256 {pkg.sha256}
use_autoreconf      yes
"""
    return TryRecipe(SHAPE_AUTORECONF, pkg.name, "net", portfile)
