"""Generate migrate.sh. Defaults to dry-run. Does not execute it."""

from __future__ import annotations

from brew_to_ports.models import Plan

HEADER = r'''#!/bin/zsh
# Generated by brew-to-ports. Review before --apply.
# Default: dry-run. Pass --apply to mutate. This script does not copy config files.
set -euo pipefail

APPLY=0
typeset -a ACKED
ACKED=()

usage() {
  echo "usage: $0 [--apply] [--i-acked-config <formula>]..." >&2
  echo "  default is dry-run (prints commands)." >&2
  exit 2
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --apply) APPLY=1 ;;
    --i-acked-config)
      [[ $# -ge 2 ]] || usage
      ACKED+=("$2")
      shift
      ;;
    -h|--help) usage ;;
    *) echo "unknown argument: $1" >&2; usage ;;
  esac
  shift
done

arch="$(uname -m)"
if [[ "$arch" != "x86_64" ]]; then
  echo "brew-to-ports: Intel x86_64 macOS only (got $arch)." >&2
  exit 1
fi

acked() {
  local name="$1"
  local x
  for x in "${ACKED[@]+${ACKED[@]}}"; do
    [[ "$x" == "$name" ]] && return 0
  done
  return 1
}

run() {
  if [[ "$APPLY" -eq 0 ]]; then
    printf 'DRY-RUN: '
    printf '%q ' "$@"
    printf '\n'
  else
    "$@"
  fi
}

if [[ "$APPLY" -eq 0 ]]; then
  echo "DRY-RUN (pass --apply to execute). No packages will be installed or uninstalled."
fi
'''


def render_script(plan: Plan) -> str:
    lines = [HEADER.rstrip(), ""]
    installs = [op for op in plan.ops if op.action == "port_install"]
    uninstalls = [op for op in plan.ops if op.action == "brew_uninstall"]

    if plan.configs:
        lines.append("# CONFIG review (not applied)")
        for cfg in plan.configs:
            lines.append(f"# CONFIG review for {cfg.brew_package} (not applied)")
            lines.append(f"#   brew:  {cfg.brew_path}")
            lines.append(f"#   ports: {cfg.guessed_ports_path}")
            extra = "yes — edit by hand, do not cp" if cfg.contains_brew_paths else "no"
            lines.append(f"#   contains brew paths: {extra}")
        lines.append("")

    lines.append("run sudo port selfupdate")
    lines.append("")

    for op in installs:
        lines.append(f"echo '--> port install {op.port_name} (from brew {op.brew_name})'")
        lines.append(f"run sudo port install {op.port_name}")
        lines.append(f"run port -q installed {op.port_name}")
        lines.append("")

    for op in uninstalls:
        if op.hold_uninstall:
            lines.append(f"echo '--> brew uninstall {op.brew_name} (held until --i-acked-config {op.brew_name})'")
            lines.append(f'if acked "{op.brew_name}"; then')
            lines.append(f"  run brew uninstall {op.brew_name}")
            lines.append("else")
            lines.append(
                f'  echo "HOLD: {op.brew_name} has config/state; pass --i-acked-config {op.brew_name} to uninstall brew copy"'
            )
            lines.append("fi")
        else:
            lines.append(f"echo '--> brew uninstall {op.brew_name}'")
            lines.append(f"run brew uninstall {op.brew_name}")
        lines.append("")

    lines.append('echo "done."')
    lines.append("")
    return "\n".join(lines)
